wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.13
    cli_version: 0.15.4
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692124314.598921
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 23
      4: 3.7.13
      5: 0.15.4
      8:
      - 5
