wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.13
    cli_version: 0.15.4
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1687801059.883
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 23
      4: 3.7.13
      5: 0.15.4
      8:
      - 1
      - 5
